"""Initial schema

Revision ID: 4627df25dde5
Revises: 
Create Date: 2026-03-14 13:19:33.471033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4627df25dde5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='Display name of the language, must be unique'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('name', name=op.f('uq_languages_name'))
    )
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False, comment='User who started this session; references auth-service'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_sessions'))
    )
    op.create_index(op.f('ix_review_sessions_user_id'), 'review_sessions', ['user_id'], unique=False)
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag; false means the phrase is hidden from the user'),
    sa.Column('source_language_id', sa.Integer(), nullable=False, comment='Language the phrase was captured from'),
    sa.Column('target_language_id', sa.Integer(), nullable=False, comment='Language the user already knows (used for the translation)'),
    sa.Column('user_id', sa.String(), nullable=False, comment='Owner of this phrase; references a user in the auth-service'),
    sa.Column('original_text', sa.String(), nullable=False, comment='Text in the source language as it was captured'),
    sa.Column('translated_text', sa.String(), nullable=False, comment='Translation of the phrase in the target language'),
    sa.Column('pronunciation', sa.String(), nullable=True, comment='Optional phonetic guide (e.g. IPA or romaji)'),
    sa.Column('last_reviewed_date', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp of the most recent review session that included this phrase'),
    sa.Column('next_review_date', sa.TIMESTAMP(timezone=True), nullable=True, comment='SM-2 scheduled date for the next review; null until the first review is completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], name=op.f('fk_phrases_source_language_id_languages')),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], name=op.f('fk_phrases_target_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phrases'))
    )
    op.create_index(op.f('ix_phrases_user_id'), 'phrases', ['user_id'], unique=False)
    op.create_table('review_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False, comment='Phrase this scheduling data belongs to'),
    sa.Column('repetition_number', sa.Integer(), server_default='0', nullable=False, comment='Number of consecutive successful reviews (resets to 0 on a failing grade)'),
    sa.Column('easiness_factor', sa.Numeric(precision=5, scale=4), server_default='2.5', nullable=False, comment='SM-2 E-factor controlling how fast the interval grows; clamped to [1.3, 2.5]'),
    sa.Column('inner_repetition_interval', sa.Integer(), server_default='0', nullable=False, comment='Current inter-repetition interval in days'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('easiness_factor BETWEEN 1.3 AND 2.5', name=op.f('ck_review_data_ck_review_data_easiness_factor')),
    sa.CheckConstraint('repetition_number >= 0', name=op.f('ck_review_data_ck_review_data_repetition_number')),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], name=op.f('fk_review_data_phrase_id_phrases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_data')),
    sa.UniqueConstraint('phrase_id', name=op.f('uq_review_data_phrase_id'))
    )
    op.create_table('review_sessions_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=False, comment='Session this attempt belongs to'),
    sa.Column('phrase_id', sa.Integer(), nullable=False, comment='Phrase that was shown to the user'),
    sa.Column('try_number', sa.SmallInteger(), nullable=False, comment='Attempt index within the session, starting at 0'),
    sa.Column('response_time', sa.Integer(), nullable=False, comment='Time the user took to answer, in milliseconds'),
    sa.Column('recall_rating', sa.SmallInteger(), nullable=False, comment='SM-2 quality of recall: 0 (complete blackout) to 5 (perfect recall)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recall_rating BETWEEN 0 AND 5', name=op.f('ck_review_sessions_phrase_ck_review_session_recall_rating')),
    sa.CheckConstraint('response_time >= 0', name=op.f('ck_review_sessions_phrase_ck_review_session_response_time')),
    sa.CheckConstraint('try_number >= 0', name=op.f('ck_review_sessions_phrase_ck_review_session_try_number')),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], name=op.f('fk_review_sessions_phrase_phrase_id_phrases')),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_review_sessions_phrase_review_session_id_review_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_sessions_phrase'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_sessions_phrase')
    op.drop_table('review_data')
    op.drop_index(op.f('ix_phrases_user_id'), table_name='phrases')
    op.drop_table('phrases')
    op.drop_index(op.f('ix_review_sessions_user_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_table('languages')
    # ### end Alembic commands ###
