"""create language, phrase, review_data, review_session and review_session_phrase tables

Revision ID: c2c1fdd62711
Revises: 
Create Date: 2026-03-05 13:18:32.357317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c1fdd62711'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('name', name=op.f('uq_languages_name'))
    )
    op.create_table('review_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_sessions'))
    )
    op.create_index(op.f('ix_review_sessions_user_id'), 'review_sessions', ['user_id'], unique=False)
    op.create_table('phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=False),
    sa.Column('pronunciation', sa.String(), nullable=True),
    sa.Column('last_reviewed_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('next_review_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], name=op.f('fk_phrases_source_language_id_languages')),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], name=op.f('fk_phrases_target_language_id_languages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phrases'))
    )
    op.create_index(op.f('ix_phrases_user_id'), 'phrases', ['user_id'], unique=False)
    op.create_table('review_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('repetition_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('easiness_factor', sa.Numeric(precision=5, scale=4), server_default='2.5', nullable=False),
    sa.Column('inner_repetition_interval', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('easiness_factor BETWEEN 1.3 AND 2.5', name=op.f('ck_review_data_ck_review_data_easiness_factor')),
    sa.CheckConstraint('repetition_number >= 0', name=op.f('ck_review_data_ck_review_data_repetition_number')),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], name=op.f('fk_review_data_phrase_id_phrases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_data'))
    )
    op.create_table('review_sessions_phrase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_session_id', sa.Integer(), nullable=False),
    sa.Column('phrase_id', sa.Integer(), nullable=False),
    sa.Column('try_number', sa.SmallInteger(), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('recall_rating', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recall_rating BETWEEN 0 AND 5', name=op.f('ck_review_sessions_phrase_ck_review_session_recall_rating')),
    sa.CheckConstraint('response_time >= 0', name=op.f('ck_review_sessions_phrase_ck_review_session_response_time')),
    sa.CheckConstraint('try_number >= 0', name=op.f('ck_review_sessions_phrase_ck_review_session_try_number')),
    sa.ForeignKeyConstraint(['phrase_id'], ['phrases.id'], name=op.f('fk_review_sessions_phrase_phrase_id_phrases')),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], name=op.f('fk_review_sessions_phrase_review_session_id_review_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_sessions_phrase'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_sessions_phrase')
    op.drop_table('review_data')
    op.drop_index(op.f('ix_phrases_user_id'), table_name='phrases')
    op.drop_table('phrases')
    op.drop_index(op.f('ix_review_sessions_user_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    op.drop_table('languages')
    # ### end Alembic commands ###
