"""Create language, streak and user tables

Revision ID: 61dd8e921998
Revises: 
Create Date: 2026-03-05 19:18:35.787595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61dd8e921998'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment="ISO display name of the language (e.g. 'English', 'Japanese')"),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_language_id', sa.Integer(), nullable=False, comment='Language the user already speaks natively'),
    sa.Column('learning_language_id', sa.Integer(), nullable=False, comment='Language the user is currently learning'),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag; false means the account is deactivated'),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False, comment="IANA timezone identifier used to calculate daily streak boundaries (e.g. 'America/New_York')"),
    sa.Column('accumulated_points', sa.Integer(), server_default='0', nullable=False, comment='Total gamification points earned across all review sessions'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accumulated_points >= 0', name='ck_users_accumulated_points'),
    sa.ForeignKeyConstraint(['learning_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['native_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_active_users', 'users', ['id'], unique=False, postgresql_where=sa.text('active = true'))
    op.create_table('streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User this streak record belongs to'),
    sa.Column('current_streak', sa.SmallInteger(), server_default='0', nullable=False, comment='Number of consecutive days the user has completed at least one review'),
    sa.Column('longest_streak', sa.SmallInteger(), server_default='0', nullable=False, comment='All-time longest consecutive-day streak the user has achieved'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_streak >= 0', name='ck_users_current_streak'),
    sa.CheckConstraint('longest_streak >= 0', name='ck_users_longest_streak'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streaks')
    op.drop_index('idx_active_users', table_name='users', postgresql_where=sa.text('active = true'))
    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
