spring.config.import=optional:file:.env[.properties]
server.port=8080
spring.application.name=api-gateway
server.address=0.0.0.0

# CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000,http://web-app:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

services.auth-url=${SERVICES_AUTH_URL:http://auth-service:8000}
services.core-url=${SERVICES_CORE_URL:http://core-service:8000}
services.forum-url=${SERVICES_FORUM_URL:http://forum-service:8003}
services.game-url=${SERVICES_GAME_URL:http://gamification-service:8002}

# Auth0 JWT validation
auth0.domain=${AUTH0_DOMAIN}
auth0.audience=${AUTH0_API_AUDIENCE}
