services:

  core_database:
    container_name: core_database
    image: postgres:16
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - core_service_database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  migration:
    container_name: core_migration
    build: .
    command: bash scripts/migrate.sh
    env_file: .env
    environment:
      POSTGRES_HOST: core_database
    depends_on:
      core_database:
        condition: service_healthy

  core_service:
    container_name: core_service
    build: .
    env_file: .env
    environment:
      POSTGRES_HOST: core_database
    ports:
      - "8000:8000"
    depends_on:
      core_database:
        condition: service_healthy

volumes:
  core_service_database: