apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: parla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: parla/core-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: POSTGRES_DB
              value: "core_db"
            - name: MONGO_DB
              value: "core_db"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5