apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: parla
spec:
  type: ClusterIP
  selector:
    app: core-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP