spring.application.name=GamificationService

# General
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
# Allows importing data from .env files
spring.config.import=optional:file:.env[.properties]

#PostgreSql
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}
#spring.datasource.url=${DEPLOYED_DB_URL}
#spring.datasource.username=${DEPLOYED_DB_USERNAME}
#spring.datasource.password=${DEPLOYED_DB_PASSWORD}
spring.jpa.database = POSTGRESQL
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
