spring.application.name=GamificationService

# General
#spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
#spring.jpa.show-sql=${JPA_SHOW_SQL}
# Allows importing data from .env files
#spring.config.import=optional:file:.env[.properties]
debug=false

#PostgreSqljdbc:postgresql://postgres:5432/GamificationService
#spring.datasource.url=jdbc:postgresql://localhost:5432/GamificationService
spring.datasource.url=jdbc:postgresql://postgres:5432/GamificationService
spring.datasource.username=Carlitos
spring.datasource.password=whistleblower2256
#spring.datasource.url=${DEPLOYED_DB_URL}
#spring.datasource.username=${DEPLOYED_DB_USERNAME}
#spring.datasource.password=${DEPLOYED_DB_PASSWORD}
spring.jpa.database = POSTGRESQL
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.docker.compose.enabled=false
#spring.data.redis.username=
#spring.data.redis.password=
