spring.application.name=GamificationService
spring.h2.console.enabled=true

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:h2:mem:test
spring.jpa.generate-ddl = true

spring.jpa.show-sql = true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop