apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: parla

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    
    spec:
      containers:
        - name: auth-service
          image: parla/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-credentials
          env:
            - name: POSTGRES_DB
              value: "auth_db"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5