events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        proxy_buffer_size        32k;
        proxy_buffers            8 32k;
        proxy_busy_buffers_size  64k;
        large_client_header_buffers 4 16k;

        # Auth0 SDK routes → Next.js
        location = /api/auth/login    { proxy_pass http://web-app:3000; }
        location = /api/auth/logout   { proxy_pass http://web-app:3000; }
        location = /api/auth/callback { proxy_pass http://web-app:3000; }
        location = /api/auth/profile  { proxy_pass http://web-app:3000; }
        location = /api/auth/token  { proxy_pass http://web-app:3000; }

        # Go gateway
        location /api/ {
            proxy_pass http://api-gateway:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffer_size        16k;
            proxy_buffers            8 16k;
            proxy_busy_buffers_size  32k;
        }

        # Next.js
        location / {
            proxy_pass http://web-app:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffer_size        16k;
            proxy_buffers            8 16k;
            proxy_busy_buffers_size  32k;
        }
    }

     server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }
}
