apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
  namespace: parla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-service
  template:
    metadata:
      labels:
        app: forum-service
    spec:
      containers:
        - name: forum-service
          image: parla/forum-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
          env:
            - name: DB_NAME
              value: "forum_db"
            - name: ENV
              value: "production"
          envFrom:
            - secretRef:
                name: forum-credentials
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 5