# ------------------------------ DEPLOYMENT ------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: forum-microservice
  template:
    metadata:
      labels:
        app: forum-microservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["forum-microservice"]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: forum-microservice
        image: vmoras/forum-microservice-container:v1.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: forum-config
          - secretRef:
              name: forum-secret
        ports:
        - containerPort: 8003

        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 5
          timeoutSeconds: 3

---

# ------------------------------ SERVICE ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  type: ClusterIP
  selector:
    app: forum-microservice
  ports:
  - port: 80
    targetPort: 8003

---

# ------------------------------ CONFIG MAP ------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-config
data:
  ENV: "local"
