# ------------------------------ DEPLOYMENT ------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: payment-microservice
  template:
    metadata:
      labels:
        app: payment-microservice
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values: ["payment-microservice"]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: payment-microservice
        image: vmoras/payment-microservice-container:v1.0.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: payment-config
          - secretRef:
              name: payment-secret
        ports:
        - containerPort: 8005

        livenessProbe:
          httpGet:
            path: /health/check
            port: 8005
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /health/check
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 2
          failureThreshold: 5
          timeoutSeconds: 3

---

# ------------------------------ SERVICE ------------------------------
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-microservice
  ports:
  - port: 80
    targetPort: 8005

---

# ------------------------------ CONFIG MAP ------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  SERVER_PORT: "8005"
  SPRING_APPLICATION_NAME: "payment-service"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_ARQUISOFT_PAYMENT: "DEBUG"
